services:
  - type: web
    name: moodlist-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GENIUS_ACCESS_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ORACLE_USER
        sync: false
      - key: ORACLE_PASSWORD
        sync: false
      - key: ORACLE_DSN
        sync: false
